DSA: [
    ArrayList,
    BinarySearchList,
    BTBFS,
    BTInOrder,
    BTPostOrder,
    BTPreOrder,
    BubbleSort,
    CompareBinaryTrees,
    DFSOnBST,
    DoublyLinkedList,
    LinearSearchList,
    MazeSolver,
    MergeSort,
    MinHeap,
    QuickSort,
    Queue,
    RingBuffer,
    Stack,
    SinglyLinkedList,
    Trie,
    TwoCrystalBalls
]