DSA: [
    ArrayList,
    BinarySearchList,
    BubbleSort,
    DoublyLinkedList,
    LinearSearchList,
    MazeSolver,
    MergeSort,
    MinHeap,
    QuickSort,
    Queue,
    RingBuffer,
    Stack,
    SinglyLinkedList,
    TwoCrystalBalls
]